services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: class-app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-class:
    build:
      context: .
      dockerfile: ./cmd/api-class/Dockerfile
    container_name: api-class
    restart: on-failure
    ports:
      - "8081:8081" # REST API
      - "50051:50051" # gRPC server
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: class-app
      POSTGRES_HOST: postgres
    volumes:
      - ./api-class:/app

  api-student:
    build:
      context: .
      dockerfile: ./cmd/api-student/Dockerfile
    container_name: api-student
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - api-class
      - postgres
    environment:
      CLASS_API_GRPC_HOST: api-class:50051
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: class-app
      POSTGRES_HOST: postgres
    volumes:
      - ./api-student:/app

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
        - api-class
        - api-student
volumes:
  postgres_data: